version: "3.2"
services:
  web:
    build:
      context: .
    volumes:
      - type: bind
        source: .
        target: /source
    ports:
      - "8000:8080"

    command: >
          bash -c "make install &&
           make run"